# Image with systemd, ssh server and an admin user

FROM rockylinux/rockylinux:9

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
#SHELL ["/bin/bash", "-c"]

# Install required systemd packages and add some more :)
RUN INSTALL_PKGS='findutils glibc-common initscripts iproute iputils tcpdump net-tools \
    traceroute mtr nano python3 sudo iperf3 vim-minimal systemd openssh-server openssh-clients' \
    && dnf makecache && dnf install -y $INSTALL_PKGS \
    && dnf clean all

RUN find /etc/systemd/system \
    /lib/systemd/system \
    -path '*.wants/*' \
    -not -name '*journald*' \
    -not -name '*systemd-tmpfiles*' \
    -not -name '*systemd-user-sessions*' \
    -print0 | xargs -0 rm -vf

    # Configure the user, password and sudo
# RUN useradd -rm -d /home/admin -s /bin/bash -g root -G sudo admin
RUN useradd -rm -d /home/admin -s /bin/bash -G wheel admin && \
    echo 'admin:admin' | chpasswd && \
    ex +"%s/^%wheel.*$/%wheel ALL=(ALL:ALL) NOPASSWD:ALL/g" -scwq! /etc/sudoers
    


COPY rocky-entrypoint.sh /docker-entrypoint.sh
ENTRYPOINT ["/docker-entrypoint.sh"]